name: Basic CI Test

on:
  workflow_dispatch:

jobs:
  basic-test:
    name: Basic CI Environment Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Basic directory check
      run: |
        echo "🔍 Current directory: $(pwd)"
        echo "🔍 Directory contents:"
        ls -la
        echo "🔍 Root files:"
        ls -la *.json *.md 2>/dev/null || echo "No JSON/MD files in root"
        
    - name: Check package.json
      run: |
        echo "🔍 Checking package.json..."
        if [ -f "package.json" ]; then
          echo "✅ package.json exists"
          echo "🔍 Package.json contents (first 10 lines):"
          head -10 package.json
        else
          echo "❌ package.json not found"
          exit 1
        fi
